#!/bin/sh

# Install oscimp extension : 2 mixers + 2 subband with FIR 32
# start/stop/restart
case "$1" in
  start)

mkdir /sys/kernel/config/device-tree/overlays/fpga
cat /root/fpga.dtbo > /sys/kernel/config/device-tree/overlays/fpga/dtbo

sleep 0.5

CORE_MODULES_DIR=/lib/modules

insmod ${CORE_MODULES_DIR}/nco_counter_core.ko



	;;
  stop)
	rmdir /sys/kernel/config/device-tree/overlays/fpga
	;;
  restart)
	
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


